# Default image (https://hub.docker.com/_/ubuntu/)
image: openjdk:11

stages:
  - build
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -yqq ant junit4
  
# Build
build_game:
  stage: build
  script:
    - ant compile
    - ant jar

# Test
test_model:
  stage: test
  script:
    - >
      ant test
      -Dlibs.junit_4.classpath=/usr/share/java/junit4.jar
      -Dlibs.hamcrest.classpath=/usr/share/java/hamcrest-core.jar
